# Generated by Django 5.0 on 2023-12-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0002_candidate_delete_candidatedirectory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='dob',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_of_experience',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
